src/objects/Character__c.object
<CustomObject>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>MostPlayedCharacter__c</fullName>
        <label>MostPlayedCharacter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Playable_Characters</valueSetName>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Gamertag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Set__c.object
<CustomObject>
    <fields>
        <fullName>Player1Character__c</fullName>
        <label>Player1Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Sets</relationshipLabel>
        <relationshipName>Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player1__c</fullName>
        <label>Player1</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Sets</relationshipLabel>
        <relationshipName>Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player2Character__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Sets (User2Character)</relationshipLabel>
        <relationshipName>Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Sets (Player2)</relationshipLabel>
        <relationshipName>Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Set</label>
    <nameField>
        <displayFormat>S-#{0000}</displayFormat>
        <label>Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SetTriggerHelper.cls
public class SetTriggerHelper {
    
    public static void getMostCharactersPlayed(Set<Id> playerIds) {
        Map<String,Integer> charactersPlayed = new Map<String,Integer>();
        Map<String,Integer> charactersPlayed2 = new Map<String,Integer>();
        
        List<Id> playersIds = new List<Id>();
        playersIds.addAll(playerIds);
        
        List<Player__c> playersToUpdate = new List<Player__c>();
        
        if(playerIds.size() > 0){
            List<Set__c> allSets = [SELECT Player1Character__c, Player2Character__c, 
                                    Player1Character__r.Name, Player2Character__r.Name
                                    FROM Set__c
                                    WHERE Player1__c IN :playerIds OR Player2__c IN :playerIds];
            
            for(Integer i = 0 ; i < playersIds.size() ; i+=2){
                
                Id player1Id = playersIds[i];
                Id player2Id = playersIds[i+1];
                
                
                for(Set__c s : allSets){
                    if(!charactersPlayed.containsKey(s.Player1Character__r.Name) && (s.Player1__c == player1Id)) {
                        charactersPlayed.put(s.Player1Character__r.Name,0);
                    }
                    else if(charactersPlayed.containsKey(s.Player1Character__r.Name) && (s.Player1__c == player1Id)){
                        charactersPlayed.put(s.Player1Character__r.Name,(charactersPlayed.get(s.Player1Character__r.Name) + 1));
                    }
                    if(!charactersPlayed2.containsKey(s.Player2Character__r.Name) && (s.Player2__c == player2Id)) {
                        charactersPlayed2.put(s.Player2Character__r.Name,0);
                    }
                    else if(charactersPlayed2.containsKey(s.Player2Character__r.Name) && (s.Player2__c == player2Id)){
                        charactersPlayed2.put(s.Player2Character__r.Name,(charactersPlayed2.get(s.Player2Character__r.Name) + 1));
                    }
                }
                
                String mostPlayedCharacter;
                Integer mostPlayedAmount = 0;
                for(String str : charactersPlayed.keySet()){
                    Integer currentPlayedAmount = charactersPlayed.get(str);
                    if(currentPlayedAmount > mostplayedAmount){
                        mostPlayedCharacter = str;
                    }
                }
                
                String mostPlayedCharacter2;
                Integer mostPlayedAmount2 = 0;
                for(String str : charactersPlayed2.keySet()){
                    Integer currentPlayedAmount2 = charactersPlayed2.get(str);
                    if(currentPlayedAmount2 > mostplayedAmount2){
                        mostPlayedCharacter2 = str;
                    }
                }
                
                playersToUpdate.add(new Player__c(Id = player1Id, MostPlayedCharacter__c = mostPlayedCharacter));
                playersToUpdate.add(new Player__c(Id = player2Id, MostPlayedCharacter__c = mostPlayedCharacter2));
            }
            
            update playersToUpdate;
        }
    }
    
}