src/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>Character_Image__c</fullName>
        <description>Displays an image of the character</description>
        <label>Character_Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Fighter_Number__c</fullName>
        <label>Fighter Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Smash_Appearance__c</fullName>
        <label>First Smash Appearance</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NotablePlayers__c</fullName>
        <description>Notable Players that play this character.</description>
        <label>NotablePlayers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <inlineHelpText>Displays what series the character is from</inlineHelpText>
        <label>Series</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speed_Value__c</fullName>
        <label>Speed Value</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Speed__c</fullName>
        <label>Speed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slow</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Fast</fullName>
                </value>
                <value>
                    <fullName>Very Fast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Style_Description__c</fullName>
        <description>Description of the fighting style of the character</description>
        <label>Style Description</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Style__c</fullName>
        <label>Style</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Versatile</fullName>
                </value>
                <value>
                    <fullName>Zoner</fullName>
                </value>
                <value>
                    <fullName>Rush Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight_Value__c</fullName>
        <label>Weight Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Allows users to filter through different weight classes</description>
        <label>Weight</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Featherweight</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MiddleWeight</fullName>
                </value>
                <value>
                    <fullName>Heavyweight</fullName>
                </value>
                <value>
                    <fullName>Super Heavyweight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Moves__c.object
<CustomObject>
    <description>Displays information about the characters moves</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Smash Attack</fullName>
                </value>
                <value>
                    <fullName>Grab</fullName>
                </value>
                <value>
                    <fullName>Throw</fullName>
                </value>
                <value>
                    <fullName>Aerial</fullName>
                </value>
                <value>
                    <fullName>Special</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Character__c</fullName>
        <description>Defines the relationship between characters and moves</description>
        <label>Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Moves</relationshipLabel>
        <relationshipName>Moves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Damage__c</fullName>
        <description>Displays the damage applied by the move</description>
        <label>Damage</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Active_Frame__c</fullName>
        <label>First Active Frame</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Move_Name__c</fullName>
        <label>Move Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Up_Frame__c</fullName>
        <label>Start Up Frame</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Moves</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Move</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CharacterPageController.cls
public class CharacterPageController {
    public Id charId{
        get {
            if( charId == null) {
                charId = apexPages.currentPage().getParameters().get('charId');
            }
            return charId;
        }
        set;
    }
    
    public Character__c character {
        get {
            if(character == null) {
                character = [SELECT Name, Series__c, First_Smash_Appearance__c, Fighter_Number__c, Speed__c, Speed_Value__c, 
									Weight__c, Weight_Value__c, Style__c, Style_Description__c, Character_Image__c, NotablePlayers__c
                            FROM Character__c
                            WHERE Id = :charId];
            }
            return character;
        }
        set;
    }
    
    public list<Moves__c> allMoves {
        get {
            if (allMoves == null) {
                allMoves = [SELECT Move_Name__c, Category__c, Damage__c, First_Active_Frame__c, Start_Up_Frame__c
                           FROM Moves__c
                           WHERE Character__c = :charId];
                setMoves(allMoves);
            }
            return allMoves;
        }
        set;
    }
    
    public list<Moves__c> Normals{
        get{
            if(Normals == null){
                Normals = new List<Moves__c>();
            }
            return Normals;
        }
        set;
    }   
    public list<Moves__c> Aerials{
        get{
            if(Aerials == null){
                Aerials = new List<Moves__c>();
            }
            return Aerials;
        }
        set;
    }   
    public list<Moves__c> smashAttacks{
        get{
            if(smashAttacks == null){
                smashAttacks = new List<Moves__c>();
            }
            return smashAttacks;
        }
        set;
    }      
    public list<Moves__c> Specials{
        get{
            if(Specials == null){
                Specials = new List<Moves__c>();
            }
            return Specials;
        }
        set;
    }   
    public list<Moves__c> Grabs{
        get{
            if(Grabs == null){
                Grabs = new List<Moves__c>();
            }
            return Grabs;
        }
        set;
    }   
    public list<Moves__c> throws{
        get{
            if(throws == null){
                throws = new List<Moves__c>();
            }
            return throws;
        }
        set;
    }   
        
    
    public void setMoves(List<Moves__c> allMoves) {
        for(Moves__c m : allMoves){
            switch on m.Category__c {
                when 'Normal' {
                    Normals.add(m);
                }
                when 'Aerial' {
                    Aerials.add(m);
                }
                when 'Smash Attack' {
                    smashAttacks.add(m);
                }
                when 'Special' {
                    Specials.add(m); 
                }
                when 'Grab' {
                    Grabs.add(m);
                }
                when 'Throw' {
                    throws.add(m); 
                }
            }
        }
    }
}