src/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>NotablePlayers__c</fullName>
        <description>Notable Players that play this character.</description>
        <label>NotablePlayers</label>
        <type>TextArea</type>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>MostPlayedCharacter__c</fullName>
        <label>MostPlayedCharacter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Playable_Characters</valueSetName>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Gamertag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerTriggerHelper.cls
public class PlayerTriggerHelper {
    public static void updateNotablePlayers (List<Player__c> playerList){
        List<Character__c> characterList = new List<Character__c>();
        List<String> charactersToGrab = new List<String>();
        for(Player__c player : playerList) {
            charactersToGrab.add(player.MostPlayedCharacter__c);
        }
        System.debug(charactersToGrab);
        characterList = [SELECT Id, Name, notablePlayers__c
                         FROM Character__c
                         WHERE Name IN :charactersToGrab];
        System.debug(characterList);
        for(Player__c player : playerList){
            for(Character__c character : characterList){
                if(player.MostPlayedCharacter__c == character.Name){
                    if(character.NotablePlayers__c == null){
                        character.NotablePlayers__c = player.name;
                    } else {
                        if(character.notablePlayers__c.contains(player.Name)){
                            break;
                        }
                      character.notablePlayers__c = character.notablePlayers__c + ', ' + player.name;
                    }
                }
            }
        }
        System.debug(characterList);
        update characterList;
    }
}