src/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>Character_Image__c</fullName>
        <description>Displays an image of the character</description>
        <label>Character_Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Speed__c</fullName>
        <label>Speed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Slow</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Fast</fullName>
                </value>
                <value>
                    <fullName>Very Fast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Style__c</fullName>
        <label>Style</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Versatile</fullName>
                </value>
                <value>
                    <fullName>Zoner</fullName>
                </value>
                <value>
                    <fullName>Rush Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Times_Played__c</fullName>
        <label>Times Played</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Allows users to filter through different weight classes</description>
        <label>Weight</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Featherweight</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MiddleWeight</fullName>
                </value>
                <value>
                    <fullName>Heavyweight</fullName>
                </value>
                <value>
                    <fullName>Super Heavyweight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AllCharactersController.cls
public class AllCharactersController {
    
    //This can be an individual character controller, holding the properties of the
    public List<Character__c> Characters {
        get{
            if(Characters == null){
                Characters = [SELECT Character_Image__c, Name FROM Character__c];
            }
            return Characters;
        }
        set;
    }
    
    public Id charId{
        get;
        set;
    }
    
    public String Weight{
        get;
        set;
    }
    
    public String Speed{
        get;
        set;
    }
    
    public String Style{
        get;
        set;
    }
    
    public Boolean allWeights{
        get;
        set;
    }
    
    public Boolean isPlayed{
        get {
            if(isPlayed == null){
                isPlayed = true;
            }
            return isPlayed;
        }
        set;
    }
    
    public String mostLeastPlayed{
        get {
            if(mostLeastPlayed == null){
                mostLeastPlayed = 'Most Played';
            }
            return mostLeastPlayed;
        }
        set;
    }
    
    public List<SelectOption> getWeights(){
        List<SelectOption> weights = new List<SelectOption>();
        weights.add(new SelectOption('-','-'));
        weights.add(new SelectOption('Featherweight','Featherweight'));
        weights.add(new SelectOption('Middleweight','Middleweight'));
        weights.add(new SelectOption('Heavyweight','Heavyweight'));
        weights.add(new SelectOption('Super Heavyweight','Super Heavyweight'));
        return weights;
    }
    
    public List<SelectOption> getSpeeds(){
        List<SelectOption> speeds = new List<SelectOption>();
        speeds.add(new SelectOption('-','-'));
        speeds.add(new SelectOption('Slow','Slow'));
        speeds.add(new SelectOption('Average','Average'));
        speeds.add(new SelectOption('Fast','Fast'));
        speeds.add(new SelectOption('Very Fast','Very Fast'));
        return speeds;
    }
    
    public List<SelectOption> getStyles(){
        List<SelectOption> styles = new List<SelectOption>();
        styles.add(new SelectOption('-','-'));
        styles.add(new SelectOption('Versatile','Versatile'));
        styles.add(new SelectOption('Rush Down','Rush Down'));
        styles.add(new SelectOption('Zoner','Zoner'));
        return styles;
    }    
    public void filterCharacters(){
        if(Weight == '-' && Speed == '-' && Style == '-' && isPlayed){//1
            Characters = [SELECT Character_Image__c, Name FROM Character__c ORDER BY Times_Played__c ASC];
        } else if(Weight != '-' && Speed == '-'  && Style == '-' && isPlayed){//2
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Weight__c = :Weight ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed != '-'  && Style == '-' && isPlayed){//3
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Speed__c = :Speed ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed == '-' && Style != '-' && isPlayed){//4
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Style__c = :Style ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed == '-' && Style == '-' && !isPlayed){//5
            Characters = [SELECT Character_Image__c, Name FROM Character__c ORDER BY Times_Played__c DESC];
        } else if(Weight != '-' && Speed != '-' && Style == '-' && isPlayed){//6
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Weight__c = :Weight AND Speed__c = :Speed ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed != '-' && Style != '-' && isPlayed){//7
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Speed__c = :Speed AND Style__c = :Style ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed == '-' && Style != '-' && !isPlayed){//8
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Style__c = :Style ORDER BY Times_Played__c DESC];
        } else if(Weight != '-' && Speed == '-' && Style == '-' && !isPlayed){//9
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Weight__c = :Weight ORDER BY Times_Played__c DESC];
        } else if(Weight != '-' && Speed != '-' && Style != '-' && isPlayed){//10
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Weight__c = :Weight AND Speed__c = :Speed AND Style__c = :Style ORDER BY Times_Played__c ASC];
        } else if(Weight == '-' && Speed != '-' && Style != '-' && !isPlayed){//11
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Speed__c = :Speed AND Style__c = :Style ORDER BY Times_Played__c DESC];
        } else if(Weight != '-' && Speed != '-' && Style != '-' && !isPlayed){//12
            Characters = [SELECT Character_Image__c, Name FROM Character__c WHERE Weight__c = :Weight AND Speed__c = :Speed AND Style__c = :Style ORDER BY Times_Played__c DESC];
        }
    }
    
    public void changePlayed(){
        if(isPlayed){
            isPlayed = false;
            mostLeastPlayed = 'Most Played';
        } else if(!isPlayed){
            isPlayed = true;
            mostLeastPlayed = 'Least Played';
        }
        filterCharacters();
        
    }
    
    public PageReference goToCharacterPage(){
        PageReference pageRef = new PageReference('/apex/CharacterPage');
        pageRef.setRedirect(true);
        pageRef.getParameters().put('charId', charId);
        return pageRef;
    }
}