src/objects/Placement__c.object
<CustomObject>
    <description>Keeps track of placements in tournament</description>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Display the rank</description>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st</fullName>
                </value>
                <value>
                    <fullName>2nd</fullName>
                </value>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>4th</fullName>
                </value>
                <value>
                    <fullName>5th</fullName>
                </value>
                <value>
                    <fullName>6th</fullName>
                </value>
                <value>
                    <fullName>7th</fullName>
                </value>
                <value>
                    <fullName>8th</fullName>
                </value>
                <value>
                    <fullName>9th</fullName>
                </value>
                <value>
                    <fullName>10th</fullName>
                </value>
                <value>
                    <fullName>11th</fullName>
                </value>
                <value>
                    <fullName>12th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Overall_Rank__c</fullName>
        <label>Overall Rank</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Gamertag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlacementCalculatorHelper.cls
public class PlacementCalculatorHelper {
    public static void updatePlacementAverage(Set<Placement__c> placement){
        //Get list of relevant Players
        List<Id> PlayerIds = new List<Id>();
        for(Placement__c placementValue : placement){
            PlayerIds.add(placementValue.Player__c);
        }
        //Do aggregate results, avging the Rank__c field, where the players are in the
        //list of player Ids, group by the Player field
        AggregateResult[] aggResults = [SELECT AVG(Rank__c)average, Player__c
                                        FROM Placement__c
                                        // WHERE Player__c IN :PlayerIds
                                        GROUP BY Player__c
                                        ORDER BY AVG(Rank__c)];
        
        //Create list of players
        List<Player__c> PlayersToUpdate = new List<Player__c>();
        List<Integer> ranksSet = new List<Integer>();
        //Loop through the aggregate results, add new players to list with the new rank field(alias average)
        for(Integer i = 0 ; i < aggResults.size() ; i++){
            Player__c player = new Player__c();
            player.Id = (Id)aggresults[i].get('Player__c');
            //player.Overall_Rank__c = Integer.valueOf(aggResults[i].get('average'));
            player.Overall_Rank__c = i + 1;
            if(ranksSet.contains(Integer.valueOf(player.Overall_Rank__c))){
                player.Overall_Rank__c = player.Overall_Rank__c++;
            }
            PlayersToUpdate.add(player);
            ranksSet.add(Integer.valueOf(player.Overall_Rank__c));
            
        }
        update PlayersToUpdate;
        
        //update the list of players
    }
}