src/objects/Placement__c.object
<CustomObject>
    <description>Keeps track of placements in tournament</description>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Display the rank</description>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st</fullName>
                </value>
                <value>
                    <fullName>2nd</fullName>
                </value>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>4th</fullName>
                </value>
                <value>
                    <fullName>5th</fullName>
                </value>
                <value>
                    <fullName>6th</fullName>
                </value>
                <value>
                    <fullName>7th</fullName>
                </value>
                <value>
                    <fullName>8th</fullName>
                </value>
                <value>
                    <fullName>9th</fullName>
                </value>
                <value>
                    <fullName>10th</fullName>
                </value>
                <value>
                    <fullName>11th</fullName>
                </value>
                <value>
                    <fullName>12th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Gamertag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Set__c.object
<CustomObject>
    <fields>
        <fullName>Player1Character__c</fullName>
        <label>Player1Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Sets</relationshipLabel>
        <relationshipName>Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player1Losses__c</fullName>
        <label>Player1Losses</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player1Wins__c</fullName>
        <label>Player1Wins</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player1__c</fullName>
        <label>Player1</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Sets</relationshipLabel>
        <relationshipName>Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player2Character__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Sets (User2Character)</relationshipLabel>
        <relationshipName>Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Player2Losses__c</fullName>
        <label>Player2Losses</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player2Wins__c</fullName>
        <label>Player2Wins</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player2</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Sets (Player2)</relationshipLabel>
        <relationshipName>Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <label>Round</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round 1</fullName>
                </value>
                <value>
                    <fullName>Round 2</fullName>
                </value>
                <value>
                    <fullName>Round 3</fullName>
                </value>
                <value>
                    <fullName>Losers Round 1</fullName>
                </value>
                <value>
                    <fullName>Losers Round 2</fullName>
                </value>
                <value>
                    <fullName>Losers Round 3</fullName>
                </value>
                <value>
                    <fullName>Losers Round 4</fullName>
                </value>
                <value>
                    <fullName>Losers Round 5</fullName>
                </value>
                <value>
                    <fullName>Semifinals</fullName>
                </value>
                <value>
                    <fullName>Finals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Sets</relationshipLabel>
        <relationshipName>Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Set</label>
    <nameField>
        <displayFormat>S-#{0000}</displayFormat>
        <label>Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Tournament_Date__c</fullName>
        <label>Tournament_Date</label>
        <type>Date</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TournamentExtension.cls
public class TournamentExtension {
    public Id tournamentId{
        get {
            if( tournamentId == null) {
                tournamentId = apexPages.currentPage().getParameters().get('tournamentId');
            }
            return tournamentId;
        }
        set;
    }
    public Tournament__c tournament{
        get {
            if(tournament == null){
                tournament = [SELECT Name, Tournament_Date__c, Location__c
                              FROM Tournament__c
                              WHERE Id = :tournamentId];
            }  
            return Tournament;
        }
        set;
    }
    public List<Placement__c> placements{
        get {
            if(placements == null) {
                placements = [SELECT Player__c, Rank__c
                              FROM Placement__c
                              WHERE Tournament__c = :tournamentId
                              ORDER BY Rank__c];
            }
            return placements;
        }
        set;
    }
    
    public List<Set__c> sets {
        get {
            if(sets == null) {
                sets = [SELECT Player1__c, Player2__c, Player1Wins__c, Player2Wins__c, Player1Losses__c, Player2Losses__c, 
                        	   Round__c, Player1Character__c, Player2Character__c
                        FROM Set__c
                        WHERE Tournament__c = :tournamentId
                        ORDER BY Round__c];
            }
            return sets;
        }
        set;
    }
    
    public PageReference backToTournaments(){
        Pagereference pageRef = new PageReference('/apex/TournamentsPage');
        pageRef.setRedirect(true);
        return pageRef;
    }
}