src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>MaxPlayers__c</fullName>
        <description>The max number of players in a tournament</description>
        <label>MaxPlayers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tournament_Date__c</fullName>
        <label>Tournament_Date</label>
        <type>Date</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TournamentsPageController.cls
public class TournamentsPageController {
   private boolean acsendingDate = true;
    public List<Tournament__c> tournaments {
       get{
           if(Tournaments == null){
               Tournaments = [SELECT Tournament_Date__c,Name,Location__c,MaxPlayers__c FROM Tournament__c];
           }
           return Tournaments;
       }
       set;
   }

   public void SortByDate(){
       if(acsendingDate == true){
           Tournaments = [SELECT Tournament_Date__c,Name,Location__c,MaxPlayers__c FROM Tournament__c ORDER BY Tournament_Date__c ASC];
           acsendingDate = false;
       }
       else if (acsendingDate == false){
           Tournaments = [SELECT Tournament_Date__c,Name,Location__c,MaxPlayers__c FROM Tournament__c ORDER BY Tournament_Date__c DESC];
           acsendingDate = true;
       }
   }
}